### PR TITLE
Update some functions

### PR DESCRIPTION
**Pull request by LinJianan**
1. Add support to Tensor
2. Add type and argument check

### CODE REVIEW

**Review by Gaoooooo — CHANGES_REQUESTED** [review]
Hey thank you much for the huge amount of work. It took me a bit because of my error on some checking/debugging, sorry about that. 

There's just one thing that I'd like changed and I'll merge - and that's gcd. I'd like to replace it with yours however, I would like yours to also support 1 argument lists. for example: 
`let a = gcd([1,2,5,6,10,12,15]);`
The quickest way that comes to mind, is since everything is written around the inputs A and B, you can change everytime you write `A` to `argument[0]` and everytime you write `B` to `argument[1]`. I'm sure there's other ways though.

And for gcd_test, please delete the test cases that are **not** yours, as it appears to conflict with your version. 

Thank you and we appreciate the contribution

**Comment by LinJianan** [comment]
OK, I update the gcd function and test. This time we can input [15, 25, 35] and it will return 5, which is the gcd of all the elements.

**Comment by LinJianan** [comment]
I finish all the functions in math lib.

**Comment by Gaoooooo** [comment]
That was alot of work, thanks much. It looks great.

**Pull request merged**
